package cpe.baldespompiers.model.type;

import java.util.Random;

//https://www.datadictionary.wales.nhs.uk/index.html#!WordDocuments/accidentandemergencydiagnosistypes.htm
public enum InjuryType {
    LACERATION("WOUND"),
    CONTUSION("WOUND"),
    ABRASION("WOUND"),
    SOFT_TISSUE_INFLAMMATION("WOUND"),
    WOUND_OTHER("WOUND"),
    GLASGOW_COMA("HEAD_INJURY"),
    DENTAL_INJURY("HEAD_INJURY"),
    HEAD_INJURY_OTHER("HEAD_INJURY"),
    OPEN_FRACTURE("FRACTURE"),
    CLOSED_FRACTURE("FRACTURE"),
    FRACTURE_DISLOCATION("FRACTURE"),
    FRACTURE_OTHER("FRACTURE"),
    SPRAIN("JOINT_INJURY"),
    DISLOCATION("JOINT_INJURY"),
    SUBLUXATION("JOINT_INJURY"),
    JOINT_INJURY_OTHER("JOINT_INJURY"),
    AMPUTATION("AMPUTATION"),
    MUSCLE_INJURY("SOFT_TISSUE_INJURY"),
    TENDON_INJURY("SOFT_TISSUE_INJURY"),
    NERVE_INJURY("SOFT_TISSUE_INJURY"),
    VISCERAL_INJURY("SOFT_TISSUE_INJURY"),
    VASCULAR_INJURY("SOFT_TISSUE_INJURY"),
    SOFT_TISSUE_INJURY_OTHER("SOFT_TISSUE_INJURY"),
    ELECTRIC("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    CHEMICAL("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    RADIATION("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    SCALD("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    SUNBURN("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    HYPERTHERMIA("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    HYPOTHERMIA("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    FROSTBITE("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    BURNS_SCALDS_AND_THERMAL_CONDITIONS_OTHER("BURNS_SCALDS_AND_THERMAL_CONDITIONS"),
    NEEDLE_STICK_INJURY("PUNCTURE_WOUNDS"),
    HUMAN_BITE("PUNCTURE_WOUNDS"),
    ANIMAL_BITE("PUNCTURE_WOUNDS"),
    INSECT_BITE_OR_STING("PUNCTURE_WOUNDS"),
    PUNCTURE_WOUNDS_OTHER("PUNCTURE_WOUNDS"),
    ALCOHOL("POISONING_OR_OVERDOSE"),
    PRESCRIBED_DRUG("POISONING_OR_OVERDOSE"),
    NON_PRESCRIBED_PURCHASED_DRUG("POISONING_OR_OVERDOSE"),
    ILLICIT_DRUG("POISONING_OR_OVERDOSE"),
    POISONING_OR_OVERDOSE_OTHER("POISONING_OR_OVERDOSE"),
    NEAR_DROWNING("DROWNING"),
    DROWNING_OTHER("DROWNING"),
    NOTIFIABLE_DISEASE("INFECTIOUS_DISEASE"),
    NON_NOTIFIABLE_DISEASE("INFECTIOUS_DISEASE"),
    SEPTICAEMIA("LOCAL_INFECTION"),
    INFECTION_OTHER("LOCAL_INFECTION"),
    ASTHMA("RESPIRATORY_CONDITIONS"),
    CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE("RESPIRATORY_CONDITIONS"),
    RESPIRATORY_CONDITIONS_OTHER("RESPIRATORY_CONDITIONS"),
    DIABETES("ENDOCRINOLOGICAL_CONDITIONS"),
    ENDOCRINOLOGICAL_CONDITIONS_OTHER("ENDOCRINOLOGICAL_CONDITIONS"),
    MYOCARDIAL_INFARCTION("CARDIOVASCULAR_CONDITIONS"),
    VASCULAR_CONDITION("CARDIOVASCULAR_CONDITIONS"),
    CARDIOVASCULAR_CONDITIONS_OTHER("CARDIOVASCULAR_CONDITIONS"),
    SEIZURE_CONVULSION("NEUROLOGICAL_CONDITIONS"),
    CEREBROVASCULAR_EVENT("NEUROLOGICAL_CONDITIONS"),
    NEUROLOGICAL_CONDITIONS_OTHER("NEUROLOGICAL_CONDITIONS"),
    GASTROINTESTINAL_CONDITIONS("GASTROINTESTINAL_CONDITIONS"),
    UROLOGICAL_CONDITIONS("UROLOGICAL_CONDITIONS"),
    DERMATOLOGICAL_CONDITIONS("DERMATOLOGICAL_CONDITIONS"),
    PSYCHOLOGICAL_PSYCHIATRIC_CONDITIONS("PSYCHOLOGICAL_PSYCHIATRIC_CONDITIONS"),
    OBSTETRIC_CONDITIONS("OBSTETRIC_CONDITIONS"),
    GYNAECOLOGICAL_CONDITIONS("GYNAECOLOGICAL_CONDITIONS"),
    HAEMATOLOGICAL_CONDITIONS("HAEMATOLOGICAL_CONDITIONS"),
    OPHTHALMIC_CONDITIONS("OPHTHALMIC_CONDITIONS"),
    RHEUMATOLOGICAL_CONDITIONS("RHEUMATOLOGICAL_CONDITIONS"),
    GENITO_URINARY_MEDICINE("GENITO_URINARY_MEDICINE"),
    EAR_NOSE_THROAT_CONDITIONS("EAR_NOSE_THROAT_CONDITIONS"),
    CHEST_PAIN_NON_CARDIAC("PAIN"),
    ABDOMINAL_PAIN("PAIN"),
    PAIN_OTHER("PAIN"),
    ALLERGY("ALLERGY"),
    CHRONIC_ALCOHOL_ABUSE("SOCIAL_PROBLEMS_HOMELESSNESS"),
    CHRONIC_DRUG_ABUSE("SOCIAL_PROBLEMS_HOMELESSNESS"),
    SOCIAL_PROBLEMS_HOMELESSNESS_OTHER("SOCIAL_PROBLEMS_HOMELESSNESS"),
    NOTHING_ABNORMAL_DETECTED("NOTHING_ABNORMAL_DETECTED"),
    DIAGNOSIS_TYPE_NOT_OTHERWISE_SPECIFIED("DIAGNOSIS_TYPE_NOT_OTHERWISE_SPECIFIED"),
    DIAGNOSIS_NOT_RECORDED("DIAGNOSIS_NOT_RECORDED");

    private static final Random PRNG = new Random();
    private String group;
    private InjuryType(String group){
        this.group=group;
    }
    public String getGroup() {
        return group;
    }
    public void setGroup(String group) {
        this.group = group;
    }

    public static InjuryType randomInjuryType()  {
        InjuryType[] injuryTypes = values();
        return injuryTypes[PRNG.nextInt(injuryTypes.length)];
    }
}
