const getFires = () => axios.get(`${API}/api/fires`);
const getVehicles = () => axios.get(`${API}/api/vehicles`);
const getFacilities = () => axios.get(`${API}/api/facilities`);
const getFacility = () => axios.get(`${API}/api/facilities/${FACILITY_ID}`);
const getEvents = () => axios.get(`${API}/api/events`);
const moveVehicle = (id, lat, lon) => axios.put(`${API}/api/vehicles/${id}/move`, { lat, lon, projection: '4326' });
const createVehicle = (data) => axios.post(`${API}/api/vehicles`, data);
const updateVehicle = (id, data) => axios.put(`${API}/api/vehicles/${id}`, data);
const deleteVehicle = (id) => axios.delete(`${API}/api/vehicles/${id}`);
const recallAllVehiclesApi = () => axios.post(`${API}/api/vehicles/recall-all`);
const resumeDispatch = () => axios.post(`${API}/api/vehicles/resume`);
const getRecallMode = () => axios.get(`${API}/api/vehicles/recall-mode`);
const recallOneVehicle = (id) => axios.post(`${API}/api/vehicles/${id}/recall`);
const cancelRecallOneVehicle = (id) => axios.delete(`${API}/api/vehicles/${id}/recall`);
